---
# defaults file for cluster-setup-role
- hosts: localhost
  connection: local
  tasks:

  - import_role: 
      name: kops/common-role
  - import_role: 
      name: kops/policy-teardown-role
  - import_role: 
      name: kops/cluster-teardown-role
