{
 "title": "Counter Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Home Line Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "home_counter" }
   ]
  },
  {
   "title": "Home Counter",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(home_counter)" }
   ]
  },
  {
   "title": "Create Line Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "create_user_counter" }
   ]
  },
  {
   "title": "Create User",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(create_user_counter)" }
   ]
  },
  {
   "title": "Login Line Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "time_login_counter" }
   ]
  },
  {
   "title": "Login Counter",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(time_login_counter)" }
   ]
  },
  {
   "title": "Add Transaction Line Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "add_transaction_counter" }
   ]
  },
  {
   "title": "Add Transaction Counter",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(add_transaction_counter)" }
   ]
  },
  {
   "title": "Get Transaction Line Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "get_transaction_counter" }
   ]
  },
  {
   "title": "Get Transaction Counter",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(get_transaction_counter)" }
   ]
  },
  {
   "title": "Delete Transaction Line Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "delete_transaction_counter" }
   ]
  },
  {
   "title": "Delete Transaction Counter",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(delete_transaction_counter)"
    }
   ]
  },
  {
   "title": "Edit Transaction Line Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "edit_transaction_counter" }
   ]
  },
  {
   "title": "Edit Transaction Counter",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(edit_transaction_counter)" }
   ]
  },
  {
   "title": "Add Attachment Line Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "add_attachment_counter" }
   ]
  },
  {
   "title": "Add Attcahmnet Counter",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 56 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(add_attachment_counter)" }
   ]
  },
  {
   "title": "Edit Attachment Line Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "edit_attachment_counter" }
   ]
  },
  {
   "title": "Edit Attcahmnet Counter",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 64 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(edit_attachment_counter)" }
   ]
  },
  {
   "title": "Delete Attachment Line Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "delete_attachment_counter" }
   ]
  },
  {
   "title": "Delete Attcahmnet Counter",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 72 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(delete_attachment_counter)" }
   ]
  },
  {
   "title": "Get Attachment Line Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "get_attachment_counter" }
   ]
  },
  {
   "title": "Get Attcahmnet Counter",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 80 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(get_attachment_counter)" }
   ]
  }
 ]
}