---

- name: Run Config file
  shell: kubectl create configmap dashconfigss --from-file=../k8s/dashboard/

- name: Install Grafana
  shell: helm install --name grafana -f values.yaml stable/grafana
  args:
    chdir: ../k8s/app/grafana


- name: Export pod
  shell: kubectl get pods --namespace default -l "app=grafana,release=grafana" -o jsonpath="{.items[0].metadata.name}"
  register: podnamegrafana

- debug:
    msg: "Pod is {{podnamegrafana.stdout}}"  

- pause:
    minutes: 10

- name: Port forward
  shell: kubectl --namespace default port-forward {{podnamegrafana.stdout}} 3000